# Generated by Django 5.0 on 2023-12-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_content_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='images'),
        ),
    ]
