# Generated by Django 5.0 on 2023-12-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
