# Generated by Django 5.0 on 2023-12-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_name_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
