# Generated by Django 5.0 on 2023-12-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_commande_paiement_effectue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='images')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='légende')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='paiement_effectue',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='paypal_payment_id',
        ),
        migrations.AddField(
            model_name='commande',
            name='quartier',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
