# Generated by Django 5.0 on 2023-12-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_shop_remove_commande_paiement_effectue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
