# Generated by Django 5.0 on 2023-12-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_photo_email_photo_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
