# Generated by Django 5.0 on 2023-12-31 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_email_blog_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.commentaire'),
        ),
    ]
