# Generated by Django 5.0 on 2024-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_commentaireshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='commentaires',
            field=models.ManyToManyField(related_name='shops', to='blog.commentaire'),
        ),
    ]
