# Generated by Django 5.0 on 2024-01-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_shop_commentaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='commentaires',
            field=models.ManyToManyField(related_name='shops', to='blog.commentaireshop'),
        ),
    ]
