# Generated by Django 5.0 on 2024-01-03 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_shop_commentaires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentaireShop',
            new_name='CommentShop',
        ),
        migrations.RenameField(
            model_name='commentshop',
            old_name='photo',
            new_name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='commentaires',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
        migrations.AddField(
            model_name='shop',
            name='caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='légende'),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
