# Generated by Django 5.0 on 2024-01-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_commentaireshop_commentshop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='blog.shop'),
        ),
    ]
