# Generated by Django 5.0.1 on 2024-01-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_commentshop_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='CommentShop',
        ),
    ]
