# Generated by Django 5.0.1 on 2024-01-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_shop_uploader_delete_commentshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
